//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBet.App.admin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="admin.DataServiceSoap")]
    public interface DataServiceSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        iBet.App.admin.LoginResponse Login(iBet.App.admin.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Login", ReplyAction="*")]
        System.IAsyncResult BeginLogin(iBet.App.admin.LoginRequest request, System.AsyncCallback callback, object asyncState);
        
        iBet.App.admin.LoginResponse EndLogin(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name userID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StartTerminal", ReplyAction="*")]
        iBet.App.admin.StartTerminalResponse StartTerminal(iBet.App.admin.StartTerminalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/StartTerminal", ReplyAction="*")]
        System.IAsyncResult BeginStartTerminal(iBet.App.admin.StartTerminalRequest request, System.AsyncCallback callback, object asyncState);
        
        iBet.App.admin.StartTerminalResponse EndStartTerminal(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name userID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StopTerminal", ReplyAction="*")]
        iBet.App.admin.StopTerminalResponse StopTerminal(iBet.App.admin.StopTerminalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/StopTerminal", ReplyAction="*")]
        System.IAsyncResult BeginStopTerminal(iBet.App.admin.StopTerminalRequest request, System.AsyncCallback callback, object asyncState);
        
        iBet.App.admin.StopTerminalResponse EndStopTerminal(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name userID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllowRun", ReplyAction="*")]
        iBet.App.admin.AllowRunResponse AllowRun(iBet.App.admin.AllowRunRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AllowRun", ReplyAction="*")]
        System.IAsyncResult BeginAllowRun(iBet.App.admin.AllowRunRequest request, System.AsyncCallback callback, object asyncState);
        
        iBet.App.admin.AllowRunResponse EndAllowRun(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name userID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        iBet.App.admin.ChangePasswordResponse ChangePassword(iBet.App.admin.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        System.IAsyncResult BeginChangePassword(iBet.App.admin.ChangePasswordRequest request, System.AsyncCallback callback, object asyncState);
        
        iBet.App.admin.ChangePasswordResponse EndChangePassword(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name a1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTransaction", ReplyAction="*")]
        iBet.App.admin.AddTransactionResponse AddTransaction(iBet.App.admin.AddTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AddTransaction", ReplyAction="*")]
        System.IAsyncResult BeginAddTransaction(iBet.App.admin.AddTransactionRequest request, System.AsyncCallback callback, object asyncState);
        
        iBet.App.admin.AddTransactionResponse EndAddTransaction(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public iBet.App.admin.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(iBet.App.admin.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string deobiet;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string userName, string password, string deobiet) {
            this.userName = userName;
            this.password = password;
            this.deobiet = deobiet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public iBet.App.admin.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(iBet.App.admin.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userID;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult, string userID) {
            this.LoginResult = LoginResult;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartTerminalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartTerminal", Namespace="http://tempuri.org/", Order=0)]
        public iBet.App.admin.StartTerminalRequestBody Body;
        
        public StartTerminalRequest() {
        }
        
        public StartTerminalRequest(iBet.App.admin.StartTerminalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StartTerminalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accountPair;
        
        public StartTerminalRequestBody() {
        }
        
        public StartTerminalRequestBody(string userID, string accountPair) {
            this.userID = userID;
            this.accountPair = accountPair;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartTerminalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartTerminalResponse", Namespace="http://tempuri.org/", Order=0)]
        public iBet.App.admin.StartTerminalResponseBody Body;
        
        public StartTerminalResponse() {
        }
        
        public StartTerminalResponse(iBet.App.admin.StartTerminalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StartTerminalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool StartTerminalResult;
        
        public StartTerminalResponseBody() {
        }
        
        public StartTerminalResponseBody(bool StartTerminalResult) {
            this.StartTerminalResult = StartTerminalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StopTerminalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StopTerminal", Namespace="http://tempuri.org/", Order=0)]
        public iBet.App.admin.StopTerminalRequestBody Body;
        
        public StopTerminalRequest() {
        }
        
        public StopTerminalRequest(iBet.App.admin.StopTerminalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StopTerminalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accountPair;
        
        public StopTerminalRequestBody() {
        }
        
        public StopTerminalRequestBody(string userID, string accountPair) {
            this.userID = userID;
            this.accountPair = accountPair;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StopTerminalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StopTerminalResponse", Namespace="http://tempuri.org/", Order=0)]
        public iBet.App.admin.StopTerminalResponseBody Body;
        
        public StopTerminalResponse() {
        }
        
        public StopTerminalResponse(iBet.App.admin.StopTerminalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StopTerminalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool StopTerminalResult;
        
        public StopTerminalResponseBody() {
        }
        
        public StopTerminalResponseBody(bool StopTerminalResult) {
            this.StopTerminalResult = StopTerminalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllowRunRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllowRun", Namespace="http://tempuri.org/", Order=0)]
        public iBet.App.admin.AllowRunRequestBody Body;
        
        public AllowRunRequest() {
        }
        
        public AllowRunRequest(iBet.App.admin.AllowRunRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllowRunRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ibetAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sbobetAccount;
        
        public AllowRunRequestBody() {
        }
        
        public AllowRunRequestBody(string userID, string ibetAccount, string sbobetAccount) {
            this.userID = userID;
            this.ibetAccount = ibetAccount;
            this.sbobetAccount = sbobetAccount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllowRunResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllowRunResponse", Namespace="http://tempuri.org/", Order=0)]
        public iBet.App.admin.AllowRunResponseBody Body;
        
        public AllowRunResponse() {
        }
        
        public AllowRunResponse(iBet.App.admin.AllowRunResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllowRunResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AllowRunResult;
        
        public AllowRunResponseBody() {
        }
        
        public AllowRunResponseBody(bool AllowRunResult) {
            this.AllowRunResult = AllowRunResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassword", Namespace="http://tempuri.org/", Order=0)]
        public iBet.App.admin.ChangePasswordRequestBody Body;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(iBet.App.admin.ChangePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPassword;
        
        public ChangePasswordRequestBody() {
        }
        
        public ChangePasswordRequestBody(string userID, string oldPassword, string newPassword) {
            this.userID = userID;
            this.oldPassword = oldPassword;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public iBet.App.admin.ChangePasswordResponseBody Body;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(iBet.App.admin.ChangePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChangePasswordResult;
        
        public ChangePasswordResponseBody() {
        }
        
        public ChangePasswordResponseBody(bool ChangePasswordResult) {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTransaction", Namespace="http://tempuri.org/", Order=0)]
        public iBet.App.admin.AddTransactionRequestBody Body;
        
        public AddTransactionRequest() {
        }
        
        public AddTransactionRequest(iBet.App.admin.AddTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string a1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string a2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string a3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string a4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string a5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string a6;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string a7;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string a8;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool a9;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool a10;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool a11;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public bool a12;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public bool a13;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public bool a14;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string a15;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public System.DateTime a16;
        
        public AddTransactionRequestBody() {
        }
        
        public AddTransactionRequestBody(
                    string a1, 
                    string a2, 
                    string a3, 
                    string a4, 
                    string a5, 
                    string a6, 
                    string a7, 
                    string a8, 
                    bool a9, 
                    bool a10, 
                    bool a11, 
                    bool a12, 
                    bool a13, 
                    bool a14, 
                    string a15, 
                    System.DateTime a16) {
            this.a1 = a1;
            this.a2 = a2;
            this.a3 = a3;
            this.a4 = a4;
            this.a5 = a5;
            this.a6 = a6;
            this.a7 = a7;
            this.a8 = a8;
            this.a9 = a9;
            this.a10 = a10;
            this.a11 = a11;
            this.a12 = a12;
            this.a13 = a13;
            this.a14 = a14;
            this.a15 = a15;
            this.a16 = a16;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTransactionResponse", Namespace="http://tempuri.org/", Order=0)]
        public iBet.App.admin.AddTransactionResponseBody Body;
        
        public AddTransactionResponse() {
        }
        
        public AddTransactionResponse(iBet.App.admin.AddTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddTransactionResponseBody {
        
        public AddTransactionResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataServiceSoapChannel : iBet.App.admin.DataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string userID {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StartTerminalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public StartTerminalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StopTerminalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public StopTerminalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AllowRunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AllowRunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceSoapClient : System.ServiceModel.ClientBase<iBet.App.admin.DataServiceSoap>, iBet.App.admin.DataServiceSoap {
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginStartTerminalDelegate;
        
        private EndOperationDelegate onEndStartTerminalDelegate;
        
        private System.Threading.SendOrPostCallback onStartTerminalCompletedDelegate;
        
        private BeginOperationDelegate onBeginStopTerminalDelegate;
        
        private EndOperationDelegate onEndStopTerminalDelegate;
        
        private System.Threading.SendOrPostCallback onStopTerminalCompletedDelegate;
        
        private BeginOperationDelegate onBeginAllowRunDelegate;
        
        private EndOperationDelegate onEndAllowRunDelegate;
        
        private System.Threading.SendOrPostCallback onAllowRunCompletedDelegate;
        
        private BeginOperationDelegate onBeginChangePasswordDelegate;
        
        private EndOperationDelegate onEndChangePasswordDelegate;
        
        private System.Threading.SendOrPostCallback onChangePasswordCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddTransactionDelegate;
        
        private EndOperationDelegate onEndAddTransactionDelegate;
        
        private System.Threading.SendOrPostCallback onAddTransactionCompletedDelegate;
        
        public DataServiceSoapClient() {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<StartTerminalCompletedEventArgs> StartTerminalCompleted;
        
        public event System.EventHandler<StopTerminalCompletedEventArgs> StopTerminalCompleted;
        
        public event System.EventHandler<AllowRunCompletedEventArgs> AllowRunCompleted;
        
        public event System.EventHandler<ChangePasswordCompletedEventArgs> ChangePasswordCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddTransactionCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iBet.App.admin.LoginResponse iBet.App.admin.DataServiceSoap.Login(iBet.App.admin.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string userName, string password, string deobiet, out string userID) {
            iBet.App.admin.LoginRequest inValue = new iBet.App.admin.LoginRequest();
            inValue.Body = new iBet.App.admin.LoginRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.deobiet = deobiet;
            iBet.App.admin.LoginResponse retVal = ((iBet.App.admin.DataServiceSoap)(this)).Login(inValue);
            userID = retVal.Body.userID;
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult iBet.App.admin.DataServiceSoap.BeginLogin(iBet.App.admin.LoginRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLogin(string userName, string password, string deobiet, System.AsyncCallback callback, object asyncState) {
            iBet.App.admin.LoginRequest inValue = new iBet.App.admin.LoginRequest();
            inValue.Body = new iBet.App.admin.LoginRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.deobiet = deobiet;
            return ((iBet.App.admin.DataServiceSoap)(this)).BeginLogin(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iBet.App.admin.LoginResponse iBet.App.admin.DataServiceSoap.EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndLogin(System.IAsyncResult result, out string userID) {
            iBet.App.admin.LoginResponse retVal = ((iBet.App.admin.DataServiceSoap)(this)).EndLogin(result);
            userID = retVal.Body.userID;
            return retVal.Body.LoginResult;
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userName = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            string deobiet = ((string)(inValues[2]));
            return this.BeginLogin(userName, password, deobiet, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            string userID = this.GetDefaultValueForInitialization<string>();
            bool retVal = this.EndLogin(result, out userID);
            return new object[] {
                    userID,
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(string userName, string password, string deobiet) {
            this.LoginAsync(userName, password, deobiet, null);
        }
        
        public void LoginAsync(string userName, string password, string deobiet, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        userName,
                        password,
                        deobiet}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iBet.App.admin.StartTerminalResponse iBet.App.admin.DataServiceSoap.StartTerminal(iBet.App.admin.StartTerminalRequest request) {
            return base.Channel.StartTerminal(request);
        }
        
        public bool StartTerminal(string userID, string accountPair) {
            iBet.App.admin.StartTerminalRequest inValue = new iBet.App.admin.StartTerminalRequest();
            inValue.Body = new iBet.App.admin.StartTerminalRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.accountPair = accountPair;
            iBet.App.admin.StartTerminalResponse retVal = ((iBet.App.admin.DataServiceSoap)(this)).StartTerminal(inValue);
            return retVal.Body.StartTerminalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult iBet.App.admin.DataServiceSoap.BeginStartTerminal(iBet.App.admin.StartTerminalRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginStartTerminal(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginStartTerminal(string userID, string accountPair, System.AsyncCallback callback, object asyncState) {
            iBet.App.admin.StartTerminalRequest inValue = new iBet.App.admin.StartTerminalRequest();
            inValue.Body = new iBet.App.admin.StartTerminalRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.accountPair = accountPair;
            return ((iBet.App.admin.DataServiceSoap)(this)).BeginStartTerminal(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iBet.App.admin.StartTerminalResponse iBet.App.admin.DataServiceSoap.EndStartTerminal(System.IAsyncResult result) {
            return base.Channel.EndStartTerminal(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndStartTerminal(System.IAsyncResult result) {
            iBet.App.admin.StartTerminalResponse retVal = ((iBet.App.admin.DataServiceSoap)(this)).EndStartTerminal(result);
            return retVal.Body.StartTerminalResult;
        }
        
        private System.IAsyncResult OnBeginStartTerminal(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userID = ((string)(inValues[0]));
            string accountPair = ((string)(inValues[1]));
            return this.BeginStartTerminal(userID, accountPair, callback, asyncState);
        }
        
        private object[] OnEndStartTerminal(System.IAsyncResult result) {
            bool retVal = this.EndStartTerminal(result);
            return new object[] {
                    retVal};
        }
        
        private void OnStartTerminalCompleted(object state) {
            if ((this.StartTerminalCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.StartTerminalCompleted(this, new StartTerminalCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void StartTerminalAsync(string userID, string accountPair) {
            this.StartTerminalAsync(userID, accountPair, null);
        }
        
        public void StartTerminalAsync(string userID, string accountPair, object userState) {
            if ((this.onBeginStartTerminalDelegate == null)) {
                this.onBeginStartTerminalDelegate = new BeginOperationDelegate(this.OnBeginStartTerminal);
            }
            if ((this.onEndStartTerminalDelegate == null)) {
                this.onEndStartTerminalDelegate = new EndOperationDelegate(this.OnEndStartTerminal);
            }
            if ((this.onStartTerminalCompletedDelegate == null)) {
                this.onStartTerminalCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnStartTerminalCompleted);
            }
            base.InvokeAsync(this.onBeginStartTerminalDelegate, new object[] {
                        userID,
                        accountPair}, this.onEndStartTerminalDelegate, this.onStartTerminalCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iBet.App.admin.StopTerminalResponse iBet.App.admin.DataServiceSoap.StopTerminal(iBet.App.admin.StopTerminalRequest request) {
            return base.Channel.StopTerminal(request);
        }
        
        public bool StopTerminal(string userID, string accountPair) {
            iBet.App.admin.StopTerminalRequest inValue = new iBet.App.admin.StopTerminalRequest();
            inValue.Body = new iBet.App.admin.StopTerminalRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.accountPair = accountPair;
            iBet.App.admin.StopTerminalResponse retVal = ((iBet.App.admin.DataServiceSoap)(this)).StopTerminal(inValue);
            return retVal.Body.StopTerminalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult iBet.App.admin.DataServiceSoap.BeginStopTerminal(iBet.App.admin.StopTerminalRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginStopTerminal(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginStopTerminal(string userID, string accountPair, System.AsyncCallback callback, object asyncState) {
            iBet.App.admin.StopTerminalRequest inValue = new iBet.App.admin.StopTerminalRequest();
            inValue.Body = new iBet.App.admin.StopTerminalRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.accountPair = accountPair;
            return ((iBet.App.admin.DataServiceSoap)(this)).BeginStopTerminal(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iBet.App.admin.StopTerminalResponse iBet.App.admin.DataServiceSoap.EndStopTerminal(System.IAsyncResult result) {
            return base.Channel.EndStopTerminal(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndStopTerminal(System.IAsyncResult result) {
            iBet.App.admin.StopTerminalResponse retVal = ((iBet.App.admin.DataServiceSoap)(this)).EndStopTerminal(result);
            return retVal.Body.StopTerminalResult;
        }
        
        private System.IAsyncResult OnBeginStopTerminal(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userID = ((string)(inValues[0]));
            string accountPair = ((string)(inValues[1]));
            return this.BeginStopTerminal(userID, accountPair, callback, asyncState);
        }
        
        private object[] OnEndStopTerminal(System.IAsyncResult result) {
            bool retVal = this.EndStopTerminal(result);
            return new object[] {
                    retVal};
        }
        
        private void OnStopTerminalCompleted(object state) {
            if ((this.StopTerminalCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.StopTerminalCompleted(this, new StopTerminalCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void StopTerminalAsync(string userID, string accountPair) {
            this.StopTerminalAsync(userID, accountPair, null);
        }
        
        public void StopTerminalAsync(string userID, string accountPair, object userState) {
            if ((this.onBeginStopTerminalDelegate == null)) {
                this.onBeginStopTerminalDelegate = new BeginOperationDelegate(this.OnBeginStopTerminal);
            }
            if ((this.onEndStopTerminalDelegate == null)) {
                this.onEndStopTerminalDelegate = new EndOperationDelegate(this.OnEndStopTerminal);
            }
            if ((this.onStopTerminalCompletedDelegate == null)) {
                this.onStopTerminalCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnStopTerminalCompleted);
            }
            base.InvokeAsync(this.onBeginStopTerminalDelegate, new object[] {
                        userID,
                        accountPair}, this.onEndStopTerminalDelegate, this.onStopTerminalCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iBet.App.admin.AllowRunResponse iBet.App.admin.DataServiceSoap.AllowRun(iBet.App.admin.AllowRunRequest request) {
            return base.Channel.AllowRun(request);
        }
        
        public bool AllowRun(string userID, string ibetAccount, string sbobetAccount) {
            iBet.App.admin.AllowRunRequest inValue = new iBet.App.admin.AllowRunRequest();
            inValue.Body = new iBet.App.admin.AllowRunRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.ibetAccount = ibetAccount;
            inValue.Body.sbobetAccount = sbobetAccount;
            iBet.App.admin.AllowRunResponse retVal = ((iBet.App.admin.DataServiceSoap)(this)).AllowRun(inValue);
            return retVal.Body.AllowRunResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult iBet.App.admin.DataServiceSoap.BeginAllowRun(iBet.App.admin.AllowRunRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAllowRun(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAllowRun(string userID, string ibetAccount, string sbobetAccount, System.AsyncCallback callback, object asyncState) {
            iBet.App.admin.AllowRunRequest inValue = new iBet.App.admin.AllowRunRequest();
            inValue.Body = new iBet.App.admin.AllowRunRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.ibetAccount = ibetAccount;
            inValue.Body.sbobetAccount = sbobetAccount;
            return ((iBet.App.admin.DataServiceSoap)(this)).BeginAllowRun(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iBet.App.admin.AllowRunResponse iBet.App.admin.DataServiceSoap.EndAllowRun(System.IAsyncResult result) {
            return base.Channel.EndAllowRun(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndAllowRun(System.IAsyncResult result) {
            iBet.App.admin.AllowRunResponse retVal = ((iBet.App.admin.DataServiceSoap)(this)).EndAllowRun(result);
            return retVal.Body.AllowRunResult;
        }
        
        private System.IAsyncResult OnBeginAllowRun(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userID = ((string)(inValues[0]));
            string ibetAccount = ((string)(inValues[1]));
            string sbobetAccount = ((string)(inValues[2]));
            return this.BeginAllowRun(userID, ibetAccount, sbobetAccount, callback, asyncState);
        }
        
        private object[] OnEndAllowRun(System.IAsyncResult result) {
            bool retVal = this.EndAllowRun(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAllowRunCompleted(object state) {
            if ((this.AllowRunCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AllowRunCompleted(this, new AllowRunCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AllowRunAsync(string userID, string ibetAccount, string sbobetAccount) {
            this.AllowRunAsync(userID, ibetAccount, sbobetAccount, null);
        }
        
        public void AllowRunAsync(string userID, string ibetAccount, string sbobetAccount, object userState) {
            if ((this.onBeginAllowRunDelegate == null)) {
                this.onBeginAllowRunDelegate = new BeginOperationDelegate(this.OnBeginAllowRun);
            }
            if ((this.onEndAllowRunDelegate == null)) {
                this.onEndAllowRunDelegate = new EndOperationDelegate(this.OnEndAllowRun);
            }
            if ((this.onAllowRunCompletedDelegate == null)) {
                this.onAllowRunCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAllowRunCompleted);
            }
            base.InvokeAsync(this.onBeginAllowRunDelegate, new object[] {
                        userID,
                        ibetAccount,
                        sbobetAccount}, this.onEndAllowRunDelegate, this.onAllowRunCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iBet.App.admin.ChangePasswordResponse iBet.App.admin.DataServiceSoap.ChangePassword(iBet.App.admin.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public bool ChangePassword(string userID, string oldPassword, string newPassword) {
            iBet.App.admin.ChangePasswordRequest inValue = new iBet.App.admin.ChangePasswordRequest();
            inValue.Body = new iBet.App.admin.ChangePasswordRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            iBet.App.admin.ChangePasswordResponse retVal = ((iBet.App.admin.DataServiceSoap)(this)).ChangePassword(inValue);
            return retVal.Body.ChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult iBet.App.admin.DataServiceSoap.BeginChangePassword(iBet.App.admin.ChangePasswordRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginChangePassword(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginChangePassword(string userID, string oldPassword, string newPassword, System.AsyncCallback callback, object asyncState) {
            iBet.App.admin.ChangePasswordRequest inValue = new iBet.App.admin.ChangePasswordRequest();
            inValue.Body = new iBet.App.admin.ChangePasswordRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            return ((iBet.App.admin.DataServiceSoap)(this)).BeginChangePassword(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iBet.App.admin.ChangePasswordResponse iBet.App.admin.DataServiceSoap.EndChangePassword(System.IAsyncResult result) {
            return base.Channel.EndChangePassword(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndChangePassword(System.IAsyncResult result) {
            iBet.App.admin.ChangePasswordResponse retVal = ((iBet.App.admin.DataServiceSoap)(this)).EndChangePassword(result);
            return retVal.Body.ChangePasswordResult;
        }
        
        private System.IAsyncResult OnBeginChangePassword(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userID = ((string)(inValues[0]));
            string oldPassword = ((string)(inValues[1]));
            string newPassword = ((string)(inValues[2]));
            return this.BeginChangePassword(userID, oldPassword, newPassword, callback, asyncState);
        }
        
        private object[] OnEndChangePassword(System.IAsyncResult result) {
            bool retVal = this.EndChangePassword(result);
            return new object[] {
                    retVal};
        }
        
        private void OnChangePasswordCompleted(object state) {
            if ((this.ChangePasswordCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ChangePasswordCompleted(this, new ChangePasswordCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ChangePasswordAsync(string userID, string oldPassword, string newPassword) {
            this.ChangePasswordAsync(userID, oldPassword, newPassword, null);
        }
        
        public void ChangePasswordAsync(string userID, string oldPassword, string newPassword, object userState) {
            if ((this.onBeginChangePasswordDelegate == null)) {
                this.onBeginChangePasswordDelegate = new BeginOperationDelegate(this.OnBeginChangePassword);
            }
            if ((this.onEndChangePasswordDelegate == null)) {
                this.onEndChangePasswordDelegate = new EndOperationDelegate(this.OnEndChangePassword);
            }
            if ((this.onChangePasswordCompletedDelegate == null)) {
                this.onChangePasswordCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnChangePasswordCompleted);
            }
            base.InvokeAsync(this.onBeginChangePasswordDelegate, new object[] {
                        userID,
                        oldPassword,
                        newPassword}, this.onEndChangePasswordDelegate, this.onChangePasswordCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iBet.App.admin.AddTransactionResponse iBet.App.admin.DataServiceSoap.AddTransaction(iBet.App.admin.AddTransactionRequest request) {
            return base.Channel.AddTransaction(request);
        }
        
        public void AddTransaction(
                    string a1, 
                    string a2, 
                    string a3, 
                    string a4, 
                    string a5, 
                    string a6, 
                    string a7, 
                    string a8, 
                    bool a9, 
                    bool a10, 
                    bool a11, 
                    bool a12, 
                    bool a13, 
                    bool a14, 
                    string a15, 
                    System.DateTime a16) {
            iBet.App.admin.AddTransactionRequest inValue = new iBet.App.admin.AddTransactionRequest();
            inValue.Body = new iBet.App.admin.AddTransactionRequestBody();
            inValue.Body.a1 = a1;
            inValue.Body.a2 = a2;
            inValue.Body.a3 = a3;
            inValue.Body.a4 = a4;
            inValue.Body.a5 = a5;
            inValue.Body.a6 = a6;
            inValue.Body.a7 = a7;
            inValue.Body.a8 = a8;
            inValue.Body.a9 = a9;
            inValue.Body.a10 = a10;
            inValue.Body.a11 = a11;
            inValue.Body.a12 = a12;
            inValue.Body.a13 = a13;
            inValue.Body.a14 = a14;
            inValue.Body.a15 = a15;
            inValue.Body.a16 = a16;
            iBet.App.admin.AddTransactionResponse retVal = ((iBet.App.admin.DataServiceSoap)(this)).AddTransaction(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult iBet.App.admin.DataServiceSoap.BeginAddTransaction(iBet.App.admin.AddTransactionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddTransaction(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddTransaction(
                    string a1, 
                    string a2, 
                    string a3, 
                    string a4, 
                    string a5, 
                    string a6, 
                    string a7, 
                    string a8, 
                    bool a9, 
                    bool a10, 
                    bool a11, 
                    bool a12, 
                    bool a13, 
                    bool a14, 
                    string a15, 
                    System.DateTime a16, 
                    System.AsyncCallback callback, 
                    object asyncState) {
            iBet.App.admin.AddTransactionRequest inValue = new iBet.App.admin.AddTransactionRequest();
            inValue.Body = new iBet.App.admin.AddTransactionRequestBody();
            inValue.Body.a1 = a1;
            inValue.Body.a2 = a2;
            inValue.Body.a3 = a3;
            inValue.Body.a4 = a4;
            inValue.Body.a5 = a5;
            inValue.Body.a6 = a6;
            inValue.Body.a7 = a7;
            inValue.Body.a8 = a8;
            inValue.Body.a9 = a9;
            inValue.Body.a10 = a10;
            inValue.Body.a11 = a11;
            inValue.Body.a12 = a12;
            inValue.Body.a13 = a13;
            inValue.Body.a14 = a14;
            inValue.Body.a15 = a15;
            inValue.Body.a16 = a16;
            return ((iBet.App.admin.DataServiceSoap)(this)).BeginAddTransaction(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iBet.App.admin.AddTransactionResponse iBet.App.admin.DataServiceSoap.EndAddTransaction(System.IAsyncResult result) {
            return base.Channel.EndAddTransaction(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndAddTransaction(System.IAsyncResult result) {
            iBet.App.admin.AddTransactionResponse retVal = ((iBet.App.admin.DataServiceSoap)(this)).EndAddTransaction(result);
        }
        
        private System.IAsyncResult OnBeginAddTransaction(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string a1 = ((string)(inValues[0]));
            string a2 = ((string)(inValues[1]));
            string a3 = ((string)(inValues[2]));
            string a4 = ((string)(inValues[3]));
            string a5 = ((string)(inValues[4]));
            string a6 = ((string)(inValues[5]));
            string a7 = ((string)(inValues[6]));
            string a8 = ((string)(inValues[7]));
            bool a9 = ((bool)(inValues[8]));
            bool a10 = ((bool)(inValues[9]));
            bool a11 = ((bool)(inValues[10]));
            bool a12 = ((bool)(inValues[11]));
            bool a13 = ((bool)(inValues[12]));
            bool a14 = ((bool)(inValues[13]));
            string a15 = ((string)(inValues[14]));
            System.DateTime a16 = ((System.DateTime)(inValues[15]));
            return this.BeginAddTransaction(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, callback, asyncState);
        }
        
        private object[] OnEndAddTransaction(System.IAsyncResult result) {
            this.EndAddTransaction(result);
            return null;
        }
        
        private void OnAddTransactionCompleted(object state) {
            if ((this.AddTransactionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddTransactionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddTransactionAsync(
                    string a1, 
                    string a2, 
                    string a3, 
                    string a4, 
                    string a5, 
                    string a6, 
                    string a7, 
                    string a8, 
                    bool a9, 
                    bool a10, 
                    bool a11, 
                    bool a12, 
                    bool a13, 
                    bool a14, 
                    string a15, 
                    System.DateTime a16) {
            this.AddTransactionAsync(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, null);
        }
        
        public void AddTransactionAsync(
                    string a1, 
                    string a2, 
                    string a3, 
                    string a4, 
                    string a5, 
                    string a6, 
                    string a7, 
                    string a8, 
                    bool a9, 
                    bool a10, 
                    bool a11, 
                    bool a12, 
                    bool a13, 
                    bool a14, 
                    string a15, 
                    System.DateTime a16, 
                    object userState) {
            if ((this.onBeginAddTransactionDelegate == null)) {
                this.onBeginAddTransactionDelegate = new BeginOperationDelegate(this.OnBeginAddTransaction);
            }
            if ((this.onEndAddTransactionDelegate == null)) {
                this.onEndAddTransactionDelegate = new EndOperationDelegate(this.OnEndAddTransaction);
            }
            if ((this.onAddTransactionCompletedDelegate == null)) {
                this.onAddTransactionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddTransactionCompleted);
            }
            base.InvokeAsync(this.onBeginAddTransactionDelegate, new object[] {
                        a1,
                        a2,
                        a3,
                        a4,
                        a5,
                        a6,
                        a7,
                        a8,
                        a9,
                        a10,
                        a11,
                        a12,
                        a13,
                        a14,
                        a15,
                        a16}, this.onEndAddTransactionDelegate, this.onAddTransactionCompletedDelegate, userState);
        }
    }
}
